version: '3'

services:
  web:
    container_name: web-django
    restart: on-failure
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3.6-management-alpine"
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "ascan"
      RABBITMQ_DEFAULT_USER: "ascan"
      RABBITMQ_DEFAULT_PASS: "ascan"
    volumes:
    - rabbitmqdata:/var/lib/rabbitmq/
    - rabbitmqlog:/var/log/rabbitmq

  consumer:
    hostname: consumer
    container_name: consumer
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    depends_on:
      - rabbitmq

volumes:
  rabbitmqdata:
  rabbitmqlog:
    driver: local
