version: '3'

services:
  web:
    restart: on-failure
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
  rabbitmq:
    restart: on-failure
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEGFAULT_USER: guest
      - RABBITMQ_DEGFAULT_PASS: guest
